site_name: NeoForge 1.21.1 Modding Course
site_description: A practical Minecraft modding course with NeoForge
# Public project site URL (free on GitHub Pages for public repos)
site_url: https://daggerspell.github.io/MinecraftModdingCourse/
repo_url: https://github.com/daggerspell/MinecraftModdingCourse
repo_name: daggerspell/MinecraftModdingCourse
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
    - header.autohide

nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Schedule: schedule.md
  - Setup: setup.md
  - Lessons:
      - 01 · Getting Started: lessons/01-getting-started.md
      - 02 · Blocks and Items: lessons/02-blocks-and-items.md
  - Assignments:
      - 01 · First Mod: assignments/01-first-mod.md
  - Resources: resources.md
  - FAQ: faq.md
  - Policies: policies.md
  - Grading: grading.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search

extra_css:
  - stylesheets/extra.css

# use_directory_urls is true by default; keeps clean URLs
