name: Convert Syllabus DOCX

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert DOCX to Markdown
        run: |
          mkdir -p docs/images
          pandoc \
            -s \
            -t gfm+yaml_metadata_block \
            --wrap=none \
            --markdown-headings=atx \
            --extract-media=docs/images \
            --metadata title="Syllabus" \
            --metadata description="Course overview, objectives, policies, and grading." \
            -o docs/syllabus.md \
            "NeoForge_1.21.1_Modding_Course_Syllabus_and_Outline.docx"

      - name: Auto-commit converted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: convert syllabus DOCX to Markdown"
          branch: ${{ github.ref_name }}
          file_pattern: |
            docs/syllabus.md
            docs/images/**
