name: Deploy MkDocs site

on:
  workflow_dispatch:
  # Enable auto-deploy when ready:
  # push:
  #   branches: [ main ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Debug: show mkdocs.yml and pip
        run: |
          echo "--- mkdocs.yml (first 120 lines) ---"
          sed -n '1,120p' mkdocs.yml || type mkdocs.yml || true
          echo "--- pip list (mkdocs*) ---"
          pip list | grep -i mkdocs || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Ensure sitemap plugin is present even if branch has older mkdocs.yml
          pip install mkdocs-sitemap

      - name: Build site
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
